### ISSUE TITLE
needed updates for 13TeV

### ISSUE THREAD

**Issue by jshlee** [vallot/CATTools#121]
*triggers
*systematics
*pileup info
*pdf

for the triggers and systematics, it would be good if the people responsible for each pog update the code or point me to the relevant information.

For the pdf, @jhgoh can you update this please?

i guess we should discuss some of this next meeting.

**Comment by jhgoh** [comment]
- PDF - updated to NNPDF3.0. Not sure on validity of re-weighting method but at least we have some info.
- Pileup - use number of reco::Vertex.

**Comment by jshlee** [comment]
- triggers are updated and now are saved individually

**Comment by jhgoh** [comment]
PU weight recipe have to be updated.

**Comment by jshlee** [comment]
i'll close this, since the remaining points are covered by other issues
