### ISSUE TITLE
genJetFlavourPlusLeptonInfos warning

### ISSUE THREAD

**Issue by jshlee** [vallot/CATTools#129]
@YoungKwonJo or @jhgoh can you fix this?

%MSG-w Configuration:  JetFlavourClustering:genJetFlavourPlusLeptonInfos@ctor  05-Aug-2015 19:05:26 CEST pre-events
Warning:
    string jets = "AntiKt"
is deprecated, please update your config file to use
    InputTag jets = AntiKt
%MSG

**Comment by jhgoh** [comment]
Some typos. Fixing it.

**Comment by jshlee** [comment]
@YoungKwonJo, why do u clone the same object?

**Comment by jhgoh** [comment]
This was solved. closing this issue.
