### ISSUE TITLE
Add hep-tools submodule to replace CatAnalyzer/scripts.

### ISSUE THREAD

**Issue by geonmo** [vallot/CATTools#140]
Hello, everyone.

Some scripts are duplicated at hep-tools repository and CATTools.

I think that CatAnalyzer/scripts can be replace to use submodule.

What do you think?

**Comment by jhgoh** [comment]
-1. hep-tools and CATTools shares create-batch but there are other scripts which are not in common set.

**Comment by geonmo** [comment]
@jhgoh Do you think that other scripts are not useful for CAT user at hep-tools?

**Comment by jhgoh** [comment]
We had some discussion on this.
hep-tools can be added as a submodule, best place to host it seem to be CommonTools/scripts.

**Comment by geonmo** [comment]
It is completed. Close this issue.
