### ISSUE TITLE
Keep GenInfoProduct to save cross section information.(auto or external)

### ISSUE THREAD

**Issue by geonmo** [vallot/CATTools#149]
Related TWiki page : https://twiki.cern.ch/twiki/bin/view/CMS/CMS-DBS-Cross-Section

As above link, ROOT files keep Xsec information at its "Run".

I did not test this feature. However, if it works, it is better to keep GenInfoProduct at CATTools.

``` bash
Handle< GenInfoProduct > gi;
evt.getRun().getByLabel( src_, gi);

double auto_cross_section = gi->cross_section(); // is automatically calculated at the end of each RUN --  units in nb
double external_cross_section = gi->external_cross_section(); // is the pre-calculated one written in the cfg file -- units is pb
```

**Comment by jhgoh** [comment]
AFAIK, this values are not recommended to be used. This value is calculated for each job sections thus based on very small statistics.

**Comment by geonmo** [comment]
For #53, we need to add cross section information to CATTuple or text(JSON or xml).

I know that famous samples' info can be found on TWiki page.However, some dataset is very difficult to find the information. 

On this case, the naive information can be useful for users.

**Comment by geonmo** [comment]
I will close this issue. Its cross section value is not enough for us.
