### ISSUE TITLE
Cleanup old branches

### ISSUE THREAD

**Issue by jhgoh** [vallot/CATTools#162]
There are some temporary branches
- https://github.com/vallot/CATTools/tree/geonmo-patch-1
- https://github.com/vallot/CATTools/tree/revert-123-cat75x
- https://github.com/vallot/CATTools/tree/revert-104-cat72x_MiniAOD

Can we delete them?

**Comment by geonmo** [comment]
Oh, I will remove patch-1 branch.

**Comment by jhgoh** [comment]
Done.
