### ISSUE TITLE
trigger matching

### ISSUE THREAD

**Issue by jshlee** [vallot/CATTools#168]
i assume some analysis would need trigger matching done...
if someone would like to volunteer.

**Comment by jhgoh** [comment]
Any idea on this?
I would imagine:
- Add std::vectorstd::string to store all matched trigger paths and modules to all objects
- Hard-code pre-defined trigger paths to give matching results - store deltaR(offline, trg). deltaR < 0 if unmatched.
- Add std::vector<int> to store user-defined trigger id in integer, add some interface to map int->string and string->int but this maybe too complicated

**Comment by jshlee** [comment]
As you mentioned, i think it might be best to use the official trigger tools already in cmssw and keep
patTriggerObjectStandAlones and edmTriggerResults_TriggerResults__HLT.
Currently patTriggerObjectStandAlones is pretty big, but we should be able to reduce it somewhat.
If we keep edmTriggerResults_TriggerResults__HLT, we no longer need to keep __catTrigger__.

**Comment by jhgoh** [comment]
Major update is done in #193. TriggerResults and Trigger objects are stored with standard data formats.

**Comment by jshlee** [comment]
closing!
