### ISSUE TITLE
Pileup reweighting

### ISSUE THREAD

**Issue by jhgoh** [vallot/CATTools#189]
Current PU re-weighting in CATTools is based on number of offline PV which is not standard one.
We are waiting for the central PU JSON and MinBias cross section & syst. uncertainty variation factors.

The true PU distributions are available in the CMSSW
- SimGeneral/MixingModule/python/mix_2015_50ns_Startup_PoissonOOTPU_cfi.py
- SimGeneral/MixingModule/python/mix_2015_25ns_Startup_PoissonOOTPU_cfi.py

There is a presentation in HWW group (Sep 3)
- https://indico.cern.ch/event/439320/session/2/contribution/28/attachments/1149023/1648504/Sep-03_HWW_RunII_Massironi.pdf
  This is based on private PU JSON by Mike and an extrapolation xsec~70000ub from P. Skands.

**Comment by jhgoh** [comment]
(info from TOP xsec meeting) No official recipe yet. Still waiting.

**Comment by jshlee** [comment]
i think this can be closed since we are upto date with it.
