### ISSUE TITLE
Production: v7-4-4 Run2 25ns on miniAODv2

### ISSUE THREAD

**Issue by jshlee** [vallot/CATTools#253]
New production on miniAODv2 samples.
Since most of the corrections are done at miniAOD level, not much would need to be done for our side.
to do:
- remove unneeded corrections
- update PileupWeightProducer (not currently working on miniAODv2)
- \+ any other changes that need to be done

**Comment by jshlee** [comment]
also, please request new features here!

**Comment by jhgoh** [comment]
I'm requesting redo the production for TTJets signals AFTER merging the PR #268. The PR will add necessary information to apply PDF weights from the LHE. To be tested : does this runs on powheg and the other ME generators?

**Comment by YoungKwonJo** [comment]
I found missing parts for ttbar mc samples in the catTuple.
https://github.com/vallot/CATTools/blob/cat75x/CatProducer/python/catEventContent_cff.py#L34
    'keep __GenTtbarCategories___*',
    'keep *_partonTop____',
    'keep __pseudoTop___*',
++++++++++
edmDumpEventContent root://cms-xrdr.sdfarm.kr:1094///xrd/store/group/CAT/TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/v7-4-4_RunIISpring15MiniAODv2-74X_mcRun2_asymptotic_v2-v3/151025_185619/0000/catTuple_1.root

## Type                                  Module                 Label             Process   

edm::TriggerResults                   "TriggerResults"       ""                "SIM"  
edm::TriggerResults                   "TriggerResults"       ""                "HLT"  
edm::TriggerResults                   "TriggerResults"       ""                "RECO"  
edm::TriggerResults                   "TriggerResults"       ""                "PAT"  
pat::PackedTriggerPrescales           "patTrigger"           ""                "PAT"  
vectorreco::GenJet                  "slimmedGenJets"       ""                "PAT"  
vectorreco::GenParticle             "prunedGenParticles"   ""                "PAT"  
edm::TriggerResults                   "TriggerResults"       ""                "CAT"  
float                                 "pileupWeight"         ""                "CAT"  
float                                 "genWeight"            "Q"               "CAT"  
float                                 "pileupWeight"         "dn"              "CAT"  
float                                 "genWeight"            "genWeight"       "CAT"  
float                                 "genWeight"            "lheWeight"       "CAT"  
float                                 "pileupWeight"         "up"              "CAT"  
float                                 "genWeight"            "x1"              "CAT"  
float                                 "genWeight"            "x2"              "CAT"  
int                                   "genWeight"            "id1"             "CAT"  
int                                   "genWeight"            "id2"             "CAT"  
int                                   "catVertex"            "nGoodPV"         "CAT"  
int                                   "catVertex"            "nPV"             "CAT"  
int                                   "pileupWeight"         "nTrueInteraction"   "CAT"  
vectorcat::Electron                 "catElectrons"         ""                "CAT"  
vectorcat::Jet                      "catJets"              ""                "CAT"  
vectorcat::Jet                      "catJetsPuppi"         ""                "CAT"  
vectorcat::MET                      "catMETs"              ""                "CAT"  
vectorcat::MET                      "catMETsPfMva"         ""                "CAT"  
vectorcat::MET                      "catMETsPuppi"         ""                "CAT"  
vectorcat::Muon                     "catMuons"             ""                "CAT"  
vector<float>                         "genWeight"            "pdfWeights"      "CAT"  
vectorpat::TriggerObjectStandAlone    "catTrigger"           ""                "CAT"  
vectorreco::Vertex                  "catVertex"            ""                "CAT"
