### ISSUE TITLE
Update spreadsheet for v7-4-5 prod

### ISSUE THREAD

**Issue by jhgoh** [vallot/CATTools#301]
Google spreadsheet is to be updated to finalize this campaign.
https://docs.google.com/spreadsheets/d/1rWM3AlFKO8IJVaeoQkWZYWwSvicQ1QCXYSzH74QyZqE/edit#gid=519625370

Please update cells with red colors. If the cell is up to date and valid, reset the cell color.

**Comment by jhgoh** [comment]
Checked dataset names, path to some MC samples, missing (now filled up) SingleTop tW sample nEvents.

**Comment by jhgoh** [comment]
@jshlee Can I assume that the 745 production is finished? If then I will close this issue and the milestone for the production.

**Comment by jshlee** [comment]
yep!
