### ISSUE TITLE
Production v7-4-6

### ISSUE THREAD

**Issue by jshlee** [vallot/CATTools#306]
Hi All,

I've added a place holder for the next production. Please update samples required.
https://docs.google.com/spreadsheets/d/1rWM3AlFKO8IJVaeoQkWZYWwSvicQ1QCXYSzH74QyZqE/edit#gid=1087889200

Other features requested:
- both gold and silver weights
- flag for gold or silver

**Comment by jshlee** [comment]
add in JER scaling factors
https://twiki.cern.ch/twiki/bin/view/CMS/JetResolution#JER_Scaling_factors_and_Uncertai

**Comment by jshlee** [comment]
also check b-tagging sf
https://twiki.cern.ch/twiki/bin/view/CMS/BtagRecommendation74X

**Comment by jshlee** [comment]
prod is ready to be processed. this will be closed now.
please open a new one when next prod is required

**Comment by jhgoh** [comment]
What is the status of current prod?

**Comment by jshlee** [comment]
3 files to go in DoubleEG/v7-4-6_Run2015D-05Oct2015-v1 then prod is finished
will send email then
