### ISSUE TITLE
cross section update

### ISSUE THREAD

**Issue by jshlee** [vallot/CATTools#318]
can someone update DYJetsToLL_M-5to50_TuneCUETP8M1_13TeV-madgraphMLM-pythia8 cross section please

**Comment by jhgoh** [comment]
These are generator level dilepton mass distributions, normalization factors are extracted by calculating N(mZ 20-50)/N(mZ 5-50). 

There is some discontinuity near M=50. I had to introduce additional factor of 1.467. This factor is nothing but just an average of ratio of nearby bin contents, 

``` python
ym2 = hZMLo.GetBinContent(hZMLo.FindBin(50-0.001)-1)+hZMHi.GetBinContent(hZMHi.FindBin(50-0.001)-1)
ym1 = hZMLo.GetBinContent(hZMLo.FindBin(50-0.001))+hZMHi.GetBinContent(hZMHi.FindBin(50-0.001))
yp1 = hZMLo.GetBinContent(hZMLo.FindBin(50+0.001))+hZMHi.GetBinContent(hZMHi.FindBin(50+0.001))
yp2 = hZMLo.GetBinContent(hZMLo.FindBin(50+0.001)+1)+hZMHi.GetBinContent(hZMHi.FindBin(50+0.001)+1)
rPatch = (ym2/ym1 + yp1/yp2)/2 # Average of ratios between nearby bins
addSF = rPatch/(ym1/yp1)
```

You can see the gen. level dilepton mass distribution before & after applying this additional SF.
![mg_nopatch](https://cloud.githubusercontent.com/assets/4388926/11727884/ed84d33c-9fc9-11e5-9812-d41b6efb5121.png)
![mg_patch130](https://cloud.githubusercontent.com/assets/4388926/11727885/edaad294-9fc9-11e5-84df-dd575e3f6928.png)

Same one for aMC@NLO sample, 10to50 are available:
![amc_nopatch](https://cloud.githubusercontent.com/assets/4388926/11727888/ede6c3da-9fc9-11e5-8a51-97412d420d8c.png)
![amc_patch146](https://cloud.githubusercontent.com/assets/4388926/11727887/edcbefe2-9fc9-11e5-8eb4-0620c553556c.png)

---

For MG 5-50 sample
- Ratio of (Theory)/(Generated) :  0.0410604983016
- Additional factor for patching two region :  1.46590165258

---

For aMC@NLO 10-50 sample
- Ratio of (Theory)/(Generated) :  0.173990772838
- Additional factor for patching two region :  1.2973723069

**Comment by jhgoh** [comment]
Patching factors are overestimated due to missing Br in the script.

# 
- Ratio of (Theory)/(Generated) =  0.0410604983016
- Additional factor for patching two region =  1.30969442057

# 
- Ratio of (Theory)/(Generated) =  0.173990772838
- Additional factor for patching two region =  1.15851991276

**Comment by jhgoh** [comment]
Numbers are going to be updated in the spreadsheet:

# 
- Ratio of (Theory)/(Generated) =  24.3543074576
- Additional factor for patching two region =  1.30969442057
- Cross section of DY sample = 6025.18
- Cross section of DYJets_MG_5to50 sample = 114559.63

# 
- Ratio of (Theory)/(Generated) =  5.74743122115
- Additional factor for patching two region =  1.15851991276
- Cross section of DY sample = 6025.17
- Cross section of DYJets_10to50 sample = 23914.65

**Comment by jhgoh** [comment]
Values are now updated. closing this issue.
