### ISSUE TITLE
Issues using 746 production

### ISSUE THREAD

**Issue by jhgoh** [vallot/CATTools#347]
Collect remaining issues discovered while using the 746 catTuple production.
### DY cross section 10-50 and 5-50 samples

@jhgoh tried a forced matching to ZJets sample introducing additional factor #318, last commit #328 
This method shows some disagreement in RECO level (spotted by @tt8888tt)
@YoungKwonJo gave a reference values by ttH group https://twiki.cern.ch/twiki/bin/viewauth/CMS/SummaryTable1G25ns
From this table, the DY cross sections are:
- DY50- : 6025.2 +39.6 -22.5 +- 225 pb 
- DY10-50 : 18610 pb 
- DY 5-50 :  71310 ± 70 
### Updated GenTop data format code

@monttj implemented updated codes for GenTop.cc with extension to L+J channel #331
Production was done separately by @hcwhwang - he (privately) reported some difference in the event size, double checks needed
### ttXX categorization issue

gen category bit is based on the implementation in the CMSSW, but this may not work on the light flavoured jets in the L+Jet channel - LF from W, nonW etc. Fix should go into the main CMSSW.
### Electron preselection

@YoungKwonJo reported a pre selection is necessary to use the triggering MVA https://twiki.cern.ch/twiki/bin/viewauth/CMS/MultivariateElectronIdentificationRun2#Recipes_for_7_4_12_Spring15_MVA
According to this twiki page, the MVA behaviour without the preselection are UNDEFINED. We are in doubt to use the preselection cuts on the catElectrons
### Lepton scale factors

Lepton scale factors are implemented recently, #333 in the DataFormat by @jshlee , #344 from @jhgoh to use cfg format. #344 gives muon SF for tightID x tightIso. The SF values are taken in the end of 2015 from each POG's (json file from muon POG twiki, table from ppt at EGM). 

No SF for cut based electron id. No SF for electron isolation.
### Pileup reweighting

Pileup reweighting is applied with the most recent json files assuming minbias xsec = 69000mb. But there are some (minor?) discrepancy. To be double checked.
### Trigger scale factors

This is missing AFAIK
### JES/JER

Fill the information

Propagation to the MET is not shown in the CATTools.
### B tagging scale factors

SF are based on CSVv2 (add more information)
### CSV reshaping

Going to be implemented in the user analysis level?
### PseudoTopProducer bug

Spotted by @kuyoun and @tt8888tt - For a workaround, analyzers have to do the lepton+neutrino combinations #323  due to the bug in the PseudoTopProducer. The problem applies only to the ttbar xsec analysis. @jhgoh should fix this problem.
### Generator weights indices information

Definition of generator weights indices are documented in the LHE header. The genWeights producer failed to store the information in some reason thus users have to take notes themselves. Most of analyses are not using this information yet for the systematic uncertainty calculation.
### TTbar dilepton kinematic reconstruction

We added kin reco algorithm from the DESY group. #163 #184 Need full detailed validation.

**Comment by jhgoh** [comment]
Summary of discussions (Jan 15)
- Muons - puppy isolation with new tool
- Electrons - preselection ID (already merged)
- Jets - New JES? - frequently updated, no update for now
- MET - we have both, NoHF, with HF, depending on analysis
- b tagging - new cMVA to be added
- gen weights - reorganize indices using LHE header information

Please add comments here if I'm missing something.

**Comment by jshlee** [comment]
update data samples
i think it would be good to attach names to the list and have a deadline of monday for tasks required to be done for production

**Comment by jhgoh** [comment]
My proposal to change gen weights, will be done with the gen weights producer.
1. Read LHE header from the run information, keep the information about where to split the weights and how to combine them
2. Store different weights in different vectors.

Exact structure to store them in separate vector<float> to be decided.

**Comment by jshlee** [comment]
also update pileup mc weights

**Comment by jhgoh** [comment]
Closing this issue as we have another one #361
