### ISSUE TITLE
ctag

### ISSUE THREAD

**Issue by YoungKwonJo** [vallot/CATTools#468]
https://github.com/vallot/CATTools/blob/cat76x/CatProducer/python/jetProducer_cfi.py
todo list for adding ctag.

**Comment by YoungKwonJo** [comment]
ref.
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/RecoBTag/Configuration/python/RecoBTag_EventContent_cff.py#L89
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/PhysicsTools/PatAlgos/python/tools/jetTools.py#L194
https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/RecoBTag/CTagging/python/cTagging_cff.py

**Comment by jhgoh** [comment]
I'm expecting inputs from the Korea U people who are working on c-tagging - what is the c tag discriminator name.

**Comment by geonmo** [comment]
Any update for this?

**Comment by YoungKwonJo** [comment]
I guess we just add the string in the code.

##  https://github.com/vallot/CATTools/blob/cat76x/CatProducer/python/jetProducer_cfi.py

catJets = cms.EDProducer('CATJetProducer',
    src = cms.InputTag('slimmedJets'),
btagNames = cms.vstring('pfCombinedInclusiveSecondaryVertexV2BJetTags','pfCombinedMVAV2BJetTags',
**"inclusiveCandidateSecondaryVerticesCvsL","pfCombinedCvsLJetTags","pfCombinedCvsBJetTags"**
),
    .....
catJetsPuppi = cms.EDProducer('CATJetProducer',
    src = cms.InputTag('slimmedJetsPuppi'),
    btagNames = cms.vstring('pfCombinedInclusiveSecondaryVertexV2BJetTagsAK4PFPuppi','pfCombinedMVAV2BJetTagsAK4PFPuppi'),

**for catJetsPuppi, I am not sure the CTag tag.

**Comment by geonmo** [comment]
I make a PR #481

**Comment by geonmo** [comment]
I merged the PR and will close this issue. 
If you faced an errors, please re-open this issue.
