### ISSUE TITLE
Prod v7-6-4

### ISSUE THREAD

**Issue by geonmo** [vallot/CATTools#502]
Now v7-6-4 is producting.

Dashboard link: 
https://dashb-cms-job-task.cern.ch/dashboard/templates/task-analysis/#user=Geonmo+Ryu&refresh=0&table=Mains&p=6&records=25&activemenu=1&pattern=*v7-6-4*&task=&from=&till=&timerange=lastWeek

**Comment by geonmo** [comment]
## Some bug for production

### On catDstar,
- Wrong status checking. -> Fix and merge #509
- Some files will be missing due to this bug.
  - Fortunately, the almost(except unknown 3 jobs) real data samples are finished without this error.

**Comment by jhgoh** [comment]
production is now close to the final. spreadsheet is updated.
File list is also available from the dedicated git repo, CATTools-datasets.

**Comment by geonmo** [comment]
I will close this issue before new sample production.
