### ISSUE TITLE
Number of events in the spreadsheet 

### ISSUE THREAD

**Issue by jhgoh** [vallot/CATTools#511]
Number of events in the common spreadsheet can introduce misunderstanding.
Current values are filled in, assuming that the samples are 100% processed. Also, the information is not practically useful for some MC samples with negative weights.

**Comment by geonmo** [comment]
Can we solve this problem to add "weighted number of events" to spreadsheet?

**Comment by jshlee** [comment]
i think its better to remove this column. 
Each analysis should calculate their own no. of events processed.

**Comment by jhgoh** [comment]
I think it's still useful to people quickly check statistics.
IMO, we can change "NEvents" to "NEntries" and fill the # of events without weighting.
For the weighted events, we can use "lumi" column by filling (xsec x NEvents with weight). There's no loss of information.

**Comment by jhgoh** [comment]
I'm filling up the spreadsheet with the new prod. The number of event field is useful to validate the file list - it will give different number if any files are missing or duplicated.

**Comment by jhgoh** [comment]
Added average weight column in the table. Closing this issue.
