### ISSUE TITLE
Separating from dileptonCommon to TTbarDilepton cross section custom part.

### ISSUE THREAD

**Issue by geonmo** [vallot/CATTools#512]
dileptonCommon의 step6 이후 내용과

DESY smeared 관련 내용은 다른 연구와 연관성이 적어 보입니다.

@kuyoun @tt8888tt  어떻게 생각하세요?

**Comment by kuyoun** [comment]
알고 있습니다. 코드를 만들기 전에 논의가 없었던 터라 기존에 있던 코드를 그대로 옮긴 것으로 알고 있습니다. 

코드 사용자끼리 논의를 하고 다시 정리를 하도록 하죠.

**Comment by YoungKwonJo** [comment]
아마도 dilepton을 위한 common한 부분과 ttbar인 부분을 나누었으면 합니다.
그리고 DESY smeard같은 부분은 다른 함수로 뺐으면 좋겠습니다.
1. parameterInit()
   이 부분에서 Desy smeared 파트는 다른 함수로 따로 정의를 해야 할것같습니다.
   예) parameterInit(), parameterInitTTbar() 이렇게 두개로요.
2. eventSelection() 
   이부분은 크게 generate level과 eventSelection으로 나누었으면 합니다.
   DESY smeared는 eventSelection에 남겨두어도 될것같구요. 그렇게 하면 ttbb는 상속후 기존 eventSelection()을 지운후 거의같은 eventSelection()을 만들어서 거의 비슷하게 하지만 DESY smeared만 빼고 ttbb에서 필요한 부분을  추가할 생각입니다.
   여기서도 크게는 두 부분으로 나눌수 있을 것같구요.
   2.1 generated level : 그리고 이 부분도 두 부분으로 나누면 좋겠습니다.
   2.1.1 common 
   2.1.2 ttbar only
   2.2 event selection for reconstructed level.
3. setBranch()
   이 부분은 조금더 세분화했으면 합니다. 왜냐면 ttbb에서 사용하지 않을 것같은 값도 많아서 입니다.
   3.1 setBranchCommon()
   3.1.1 setBranchCommon() : dilepton only in reconstructed level
   3.1.2 setBranchRecoTTbar(): ttbar reco as DESY smeared
   3.1.3 setBranchGen() : generated info for common 
   3.1.4 setBranchGenTtbar() : generated ttbar info for common 
   3.2 setBranchCustom()
   참고로, 변수선언 부분도 이 세부 항목 별로 줄의 위치나 부분이 
   나누어 놓으면 좋을 것같습니다.
4. resetBr()
   그래서 3. setBranch()에서 나눈것처럼 비슷한 방법으로 나누어 주시면 좋겠습니다. 그러면 더욱더 선택적으로 접근이 가능할것같습니다.

**Comment by jhgoh** [comment]
일단 migration 첫번째 단계로 kinsolver파트를 common모듈에서 빼 놓고 cross section analysis 코드 쪽에서 나중에 다시 넣는 것으로 했으면 하는데 어떤가요?
https://github.com/vallot/CATTools/compare/cat76x...jhgoh:BetterDilepCommon?expand=1

사실 개인적으로는 코드가 더 복잡해지지 않을까 걱정이 있어요.

**Comment by kuyoun** [comment]
저도 고정환박사님과 같은 의견입니다. 복잡하게 하지말고, common 에서 kinsolver 에 관한부분을 지우고, cross-section 코드를 따로 두는게 좋겠습니다. ttbb와 cross-section은 사용하는 gen 정의가 완전히 다르니, genpart 도 필요하다면 분리시키고요. 

어떤식으로 만들더라도 각자 코드를 변형시킬텐데 그리 길지 않은 코드를 함수로 빼는 수고가 필요하지 않다고 생각됩니다. 제 생각에도 결국에는 더 복잡한 코드로 변형될 가능성이 크다고 봅니다.
