### ISSUE TITLE
Prod v7-6-5

### ISSUE THREAD

**Issue by geonmo** [vallot/CATTools#522]
This production data will save to KNU tier3 (cms02.knu.ac.kr)

**Comment by jshlee** [comment]
- gen/pdf weights
- added ip transverse significance for muons and electrons
- jet - update pileup ID

**Comment by jhgoh** [comment]
Will there be the legacy prod with these changes?

**Comment by geonmo** [comment]
@jshlee Do we have a PR about jet-pileup ID?

**Comment by geonmo** [comment]
Now, I just start to test for 1 miniaod file.

**Comment by jshlee** [comment]
instructions for PileupJetID
https://twiki.cern.ch/twiki/bin/viewauth/CMS/PileupJetID#Information_for_13_TeV_data_AN1
does anyone want to apply this?

**Comment by geonmo** [comment]
@jshlee @jhgoh I made issues #527 and #528 to handle.

**Comment by jshlee** [comment]
heads up for new crab script for production
source /cvmfs/cms.cern.ch/crab3/crab_light.sh

**Comment by geonmo** [comment]
"crab_light.sh" is not compatable with submitCrab job.
Production Status : 
![image](https://cloud.githubusercontent.com/assets/4969463/15537318/a097f71a-22b0-11e6-9414-d8e40cdf7a9e.png)

**Comment by geonmo** [comment]
Production is finished.
Please, see the https://docs.google.com/spreadsheets/d/1rWM3AlFKO8IJVaeoQkWZYWwSvicQ1QCXYSzH74QyZqE/edit#gid=773772766

**Comment by geonmo** [comment]
dataset file lists were uploaded to "https://github.com/vallot/CATTools-dataset/tree/v765"

**Comment by jhgoh** [comment]
Found tiny amount of negative weight events in POWHEG VBF HtoMuMu sample

![screenshot-1](https://cloud.githubusercontent.com/assets/4388926/15608339/9e614a4a-2419-11e6-9b8b-4a07a70c9682.png)

**Comment by jhgoh** [comment]
Average weight column in the spreadsheet is complete.

**Comment by jhgoh** [comment]
I think the production is now finalized and ready to be used by analyzers.

**Comment by jhgoh** [comment]
There was lumi mask issue #546 
Analyzers have to remove {"256801": [[73, 74]], "256842": [[131, 132]]} manually.

**Comment by jhgoh** [comment]
The catDataset is updated to include average weight and "type" field. catGetDatasetInfo is updated as well, #548

**Comment by jhgoh** [comment]
Closing this issue as the campaign is finished.
