### ISSUE TITLE
dataset management

### ISSUE THREAD

**Issue by jshlee** [vallot/CATTools#53]
using either JSON or xml to bind dataset/reference, globaltags, cfg/cross section info, number of events

be able to be read by analysis and crab submitting scripts /and displayed on web if possible

**Comment by geonmo** [comment]
To support Xsec information is required next release.

**Comment by jshlee** [comment]
can you document this in the twiki?
or we can add in a file list in the analyser dir

**Comment by jhgoh** [comment]
One possible solution is to save sample info in google spreadsheet and export to csv format.

https://docs.google.com/spreadsheets/d/1rWM3AlFKO8IJVaeoQkWZYWwSvicQ1QCXYSzH74QyZqE/edit?usp=sharing
- https://docs.google.com/spreadsheets/d/1rWM3AlFKO8IJVaeoQkWZYWwSvicQ1QCXYSzH74QyZqE/pub?gid=0&single=true&output=csv
- https://docs.google.com/spreadsheets/d/1rWM3AlFKO8IJVaeoQkWZYWwSvicQ1QCXYSzH74QyZqE/pub?gid=1289302456&single=true&output=csv

These csv files can be parsed by a python script to generate fileList + cross section JSON file then passed to user analysis macros.

**Comment by jhgoh** [comment]
"makeFileList" is updated (with new name getDatasetInfo) to retrieve dataset information from the google doc.

**Comment by jhgoh** [comment]
getDatasetInfo is updated. It produces simple txt formatted filelist to be used from create-batch or other tools.
JSON output can be used from the python scripts for plotting.

**Comment by jhgoh** [comment]
I think this issue can be closed since we have google doc -> CSV -> JSON interface.
