### ISSUE TITLE
InvalidReference Problem during CATTupling using lepton+Jet Synchronization file.

### ISSUE THREAD

**Issue by geonmo** [vallot/CATTools#569]
Hello, everyone.

I faced some problem about invalid reference problem during CATTupling.

``` bash
----- Begin Fatal Exception 20-Jun-2016 20:50:05 KST-----------------------
An exception of category 'InvalidReference' occurred while
   [0] Processing run: 1 lumi: 45859 event: 11453445
   [1] Running path 'catOutpath'
   [2] Calling event method for module PoolOutputModule/'catOut'
   [3] Calling produce method for unscheduled module CATJetProducer/'catJets'
   [4] Calling produce method for unscheduled module PATJetUpdater/'patJetsUpdated'
   [5] Calling produce method for unscheduled module PileupJetIdProducer/'pileupJetIdUpdated'
Exception Message:
BadRefCore RefCore: Request to resolve a null or invalid reference to a product of type 'std::vector<reco::Vertex>' has been detected.
Please modify the calling code to test validity before dereferencing.
----- End Fatal Exception -------------------------------------------------
20-Jun-2016 20:50:06 KST  Closed file root://cms-xrdr.sdfarm.kr:1094//xrd/store/user/geonmo/13TeV_miniaod/Sync/76x/Sync_76X_MC_LJ.root
```

I used "root://xrootd.unl.edu//store/mc/RunIISpring15MiniAODv2/TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/MINIAODSIM/74X_mcRun2_asymptotic_v2-v3/60000/00181849-176A-E511-8B11-848F69FD4C94.root" as inputFiles.

I already xrdcopy from external to KISTI. Please, look at "root://cms-xrdr.sdfarm.kr:1094//xrd/store/user/geonmo/13TeV_miniaod/Sync/76x/Sync_76X_MC_LJ.root"

**Comment by geonmo** [comment]
Well, I found that this input file was created by 74X release. Maybe, it can be a reason for this problem.
However, On [TTbarXSecSynchronization](https://twiki.cern.ch/twiki/bin/view/CMS/TTbarXSecSynchronization), it was tested by other group.

**Comment by jshlee** [comment]
@geonmo - can you provide the setup u used so that I can reproduce this error

**Comment by geonmo** [comment]
@jshlee I setup as "2016 March v7-6-5" on wiki page and just do "cmsRun PAT2CAT_cfg.py inputFiles=root://cms-xrdr.sdfarm.kr:1094//xrd/store/user/geonmo/13TeV_miniaod/Sync/76x/Sync_76X_MC_LJ.root" on CATTools/CatProducer/prod.

**Comment by geonmo** [comment]
After adding some command, it works.

``` bash
process.catElectrons.electronIDs = process.catElectrons.electronIDs[:-2]
process.patJetsUpdated.userData.userFloats.src=[]
```

Maybe, this problem came from difference between 74X and 76X.

However, can we determine electronIDs on runtime(at python) using input file?

**Comment by jshlee** [comment]
you can uncomment the lines in https://github.com/vallot/CATTools/blob/cat76x/CatProducer/python/catTools_cff.py#L134-L153

btw, I dont see any problems with catJets

**Comment by geonmo** [comment]
Anyway, I can solve this problem. Close the this issue.
Thanks!
