### ISSUE TITLE
corrections on the fly

### ISSUE THREAD

**Issue by jshlee** [vallot/CATTools#57]
add corrections on the fly features

**Comment by jhgoh** [comment]
Since the JES/JER uncertainty routine is going to be changed, this can be also added to CATJetProducer.

**Comment by jshlee** [comment]
yep and we should do the same for the leptons.
I guess this depends on how quickly people want the corrections to be done.
corrections during cattuple->cattuple or cattuple->flat ntuple would be the fastest.

**Comment by jshlee** [comment]
closing - reopen if this is still an issue
