### ISSUE TITLE
 MET group recommendations for analyses targeting ICHEP

### ISSUE THREAD

**Issue by YoungKwonJo** [vallot/CATTools#578]
https://hypernews.cern.ch/HyperNews/CMS/get/met/469.html

MET Filters:

The twiki with all the recommendations is here: https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2

Note that many of the 2015 filters will be re-used:
- primary vertex filter
- HBHE noise filter
- HBHEiso noise filter
- ee badSC noise filter
- ECAL TP filter

https://github.com/cms-sw/cmssw/blob/CMSSW_7_6_X/PhysicsTools/PatAlgos/python/slimming/metFilterPaths_cff.py

---

I guess we need to update the lines.
https://github.com/vallot/CATTools/blob/cat76x/CatAnalyzer/python/filters_cff.py#L18-22

**Comment by YoungKwonJo** [comment]
### MiniAOD 76X v2 (produced with the CMSSW_7_6_2 and later releases )

---

#individual filters 
Flag_HBHENoiseFilter TO BE USED 
Flag_HBHENoiseIsoFilter TO BE USED 
Flag_CSCTightHalo2015Filter TO BE USED 
Flag_EcalDeadCellTriggerPrimitiveFilter TO BE USED 
Flag_goodVertices TO BE USED 
Flag_eeBadScFilter TO BE USED 
Flag_chargedHadronTrackResolutionFilter do not use - those are under study 76X 
Flag_muonBadTrackFilter do not use - those are under study for 76X

---

**Comment by YoungKwonJo** [comment]
https://github.com/vallot/CATTools/pull/580

**Comment by jhgoh** [comment]
80x cattools modification to apply MET recipe is under preparation

**Comment by jhgoh** [comment]
muon/ch. hadron related filters are to be ran during the catTuple production.

**Comment by jhgoh** [comment]
Issue solved.
