### ISSUE TITLE
jan mc production

### ISSUE THREAD

**Issue by jshlee** [vallot/CATTools#58]
list of mc samples to be added

**Comment by kuyoun** [comment]
phys14 samples:

/TTJets_MSDecaysCKM_central_Tune4C_13TeV-madgraph-tauola/Phys14DR-PU20bx25_PHYS14_25_V1-v1/

/DYJetsToLL_M-50_13TeV-madgraph-pythia8/Phys14DR-PU20bx25_PHYS14_25_V1-v1/

/T_tW-channel-DR_Tune4C_13TeV-CSA14-powheg-tauola/Phys14DR-PU20bx25_PHYS14_25_V1-v1/

/Tbar_tW-channel-DR_Tune4C_13TeV-CSA14-powheg-tauola/Phys14DR-PU20bx25_PHYS14_25_V1-v1/

/WJetsToLNu_13TeV-madgraph-pythia8-tauola/Phys14DR-PU20bx25_PHYS14_25_V1-v1/

**Comment by jshlee** [comment]
what about the samples for ttbb?

**Comment by monttj** [comment]
ttbb is currently extracted from ttbar sample.
it will be improved if we have exclusive ttbar + 2 jets sample in the future, which I am hoping.

**Comment by geonmo** [comment]
Which CMSSW version shall we use? CMSSW_7_2_2_patch1 like "Readme.md"?

**Comment by jhgoh** [comment]
@kuyoun, for clearness, CSA14 keyword in single top sample are ignorable and they are valid Phys14 samples, right?

**Comment by geonmo** [comment]
@jhgoh As I know, Yes. These singletop sample are valid Phys14 samples.

**Comment by kuyoun** [comment]
I am going to use 720 which is used for Phys14 generation. tW sample named CSA14, but also named Phys14. We can use them. That is only tW sample that I know.

**Comment by jshlee** [comment]
if its going to be run on miniaod, the cmssw doesnt matter too much

**Comment by jhgoh** [comment]
Before submitting it, I would like to suggest to do test with background samples such as DY and single top.
PseudoTop is supposed to be OK with non-ttbar cases, but need testing.

**Comment by jshlee** [comment]
yep, i think its a good idea
we should test a bit then start production tomorrow or so

**Comment by jshlee** [comment]
also, a list of triggers needed would be good

**Comment by geonmo** [comment]
On KISTI, DY sample is already transferred but singtops are not existed.
I will request a phedex these miniaod samples tomorrow if no one reject.

**Comment by kuyoun** [comment]
Yes, please. FYI, I requested all AODSIM samples(DY, tW, tbarW, WJ).

**Comment by geonmo** [comment]
DY test with PR#59, (DY miniAOD : 56 files / 2015/01/29 )
32/56 failed , 24/56 Success. ( xrootd fallback problem.)
It was reported at Computing Resource meeting already. However, I will report again using email to Dr.Bae.

**Comment by geonmo** [comment]
Each file have 100k events and  "Real 32min / User  9min" is consumed for each file.
So, I caculated that total time of 1 cattupling(from miniAOD) will be spent 480 hours(1 file : 30min).

**Comment by geonmo** [comment]
I found my mistake to confuse directory(previous one).
Each file have 50k events and time elapsed "Real 9 min / user 6 min" 
I re-run test shot for DY and WJets to check. Please, ignore above test result and error.

**Comment by jshlee** [comment]
did you run it on crab3 or locally?

**Comment by geonmo** [comment]
I ran this tests using create-batch.
All of jobs are successfully completed.

**Comment by kuyoun** [comment]
Production with AOD samples are done: 
catTuples are stored at kisti:
/cms/data/xrd/store/user/youn/cat700_phy14_tw_2025_aod
/cms/data/xrd/store/user/youn/cat700_phy14_dy_2025_aod
/cms/data/xrd/store/user/youn/cat700_phy14_tbw_2025_aod
/cms/data/xrd/store/user/youn/cat700_phy14_wj_2025_aod
/cms/data/xrd/store/user/youn/cat700_phy14_ttbar_2025_aod

**Comment by jshlee** [comment]
can you send this message also to cat-tools@cern.ch

**Comment by geonmo** [comment]
Prudction with miniAOD Samples are completed.
Location of CATNtuples at KISTI : 
/cms/data/xrd/store/user/geonmo/cat700_phy14_tw_2025_miniaod
/cms/data/xrd/store/user/geonmo/cat700_phy14_dy_2025_miniaod
/cms/data/xrd/store/user/geonmo/cat700_phy14_tbw_2025_miniaod
/cms/data/xrd/store/user/geonmo/cat700_phy14_ttbar_2025_miniaod
/cms/data/xrd/store/user/geonmo/cat700_phy14_wj_2025_miniaod

**Comment by jhgoh** [comment]
I asked to Chanwook and Donghyun to make some root macro(chanwook) and EDAnalyzer(donghyun) for their exercise.
Then we can make those output for the validation in the future.

**Comment by kuyoun** [comment]
ee: 
HLT_Ele23_Ele12_CaloId_TrackId_Iso_v1
mm: 
HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsonVVL_v1  
em: 
HLT_Mu23_TrkIsoVVL_Ele12_Gsf_CaloId_TrackId_Iso_MediumWP_v1
HLT_Mu8_TrkIsoVVL_Ele23_Gsf_CaloId_TrackId_Iso_MediumWP_v1

**Comment by gbyu** [comment]
Trigger path in Phys14 dataset is just same with the 8TeV datasets unless running step2 manually. 

Thereby, 
mu+jets: HLT_IsoMu24_eta2p1_v
e+jets: HLT_Ele27_WP80_v

**Comment by jshlee** [comment]
all triggers have been added in my pull request

**Comment by jshlee** [comment]
closing this since we are starting a feb production
