### ISSUE TITLE
Production wiki in English

### ISSUE THREAD

**Issue by brochero** [vallot/CATTools#599]
Can we have a English version of:
https://github.com/vallot/CATTools/wiki/CatProduction

**Comment by jshlee** [comment]
+1

**Comment by geonmo** [comment]
Hello, I made a draft verion about Production wiki's English version.
https://github.com/vallot/CATTools/wiki/CatProduction-in-English

**Comment by jhgoh** [comment]
Should we remove Korean version of the wiki page? or keep both?

**Comment by jshlee** [comment]
i think having just an english page would be better

**Comment by jshlee** [comment]
@geonmo - can you do this

**Comment by geonmo** [comment]
Well, I changed title **Production in English** to **Production**. Maybe, it is better to remove korean page but I kept that.

**Comment by geonmo** [comment]
If anyone do not have a comment, I will close this issue before tomorrow.
