### ISSUE TITLE
Post-ICHEP production v801

### ISSUE THREAD

**Issue by jhgoh** [vallot/CATTools#600]
We are going to produce new sample for post-ICHEP period.
- Summary of MiniAOD recipes: [CATToolsTopAnalysis](https://twiki.cern.ch/twiki/bin/view/CMS/CATToolsTopAnalysis)
- Spreadsheet : [#gid=1981960528](https://docs.google.com/spreadsheets/d/1rWM3AlFKO8IJVaeoQkWZYWwSvicQ1QCXYSzH74QyZqE/edit#gid=1981960528)
- JSON file [Cert_271036-277148_13TeV_PromptReco_Collisions16_JSON.txt](https://cms-service-dqm.web.cern.ch/cms-service-dqm/CAF/certification/Collisions16/13TeV/Cert_271036-277148_13TeV_PromptReco_Collisions16_JSON.txt)

**Comment by jhgoh** [comment]
CMSSW recipes are updated https://github.com/vallot/cmssw/pull/18

**Comment by hcwhwang** [comment]
Checked newest JSON file  [Cert_271036-277148_13TeV_PromptReco_Collisions16_JSON.txt](https://cms-service-dqm.web.cern.ch/cms-service-dqm/CAF/certification/Collisions16/13TeV/Cert_271036-277148_13TeV_PromptReco_Collisions16_JSON.txt)
Not included in CATTools yet. Will be added.
New pileup weight values should be calculated.

**Comment by jhgoh** [comment]
JSON file and updated PU weights are calculated. They are standing in #605

**Comment by jshlee** [comment]
will close this, as the new prod is running
