### ISSUE TITLE
b-tagging SFs with BTV HIP mitigation

### ISSUE THREAD

**Issue by YoungKwonJo** [vallot/CATTools#613]
latest b-tagging SFs with BTV HIP mitigation here.

/afs/cern.ch/user/l/lwming/public/csvSFs2016/HIP_12p9_9_7_set/ 

There were calculated using the full ICHEP datasets(BCD, 12.9/fb), and BTV HIP mitigation is applied to both Data and MC

**Comment by YoungKwonJo** [comment]
/afs/cern.ch/user/l/lwming/public/csvSFs2016

**Comment by jshlee** [comment]
what is the status of this???

**Comment by YoungKwonJo** [comment]
https://indico.cern.ch/event/565329/contributions/2283640/attachments/1326958/1992396/BTV_HIPrepord_PPD.pdf

I also sent forward of few messages from TTH group to cat-tools@cern.ch.

**Comment by jhgoh** [comment]
The "new" SF from TTH group(Nov.1) is to be retrieved from /afs/cern.ch/user/l/lwming/public/csvSFs2016/HIP_12p9_9_7_set/

**Comment by jhgoh** [comment]
Recipe for the workarea setup is created. https://github.com/vallot/CATTools/wiki#2016-december-v8-0-3-in-preparation
This is not final recipe.

**Comment by jhgoh** [comment]
Can be done in analysis level - to be done in parallel to the new production,.

**Comment by jhgoh** [comment]
Seems to be there's updated version for 36.5fb under /afs/cern.ch/user/l/lwming/public/2017csvSFs

**Comment by jhgoh** [comment]
A PR to solve this problem is made and merged. Closing this issue.
