### ISSUE TITLE
Recipes for MiniAOD 80X version3

### ISSUE THREAD

**Issue by jhgoh** [vallot/CATTools#624]
Need to follow up recipes to use MiniAOD 80X version3
https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookMiniAOD#Run2016_23Sept2016_ReReco_80X_ve

Changes will be summarized in https://twiki.cern.ch/twiki/bin/viewauth/CMS/CATToolsTopAnalysis

**Comment by jshlee** [comment]
yep this will be done for the next prod v8-0-3

**Comment by jhgoh** [comment]
spreadsheet is created https://docs.google.com/spreadsheets/d/1rWM3AlFKO8IJVaeoQkWZYWwSvicQ1QCXYSzH74QyZqE/edit#gid=1456963899

**Comment by jshlee** [comment]
all the MCs need to be updated

**Comment by jhgoh** [comment]
I think most of recipes (up to now) which have to be applied at the production level are done.
MCs are to be updated later.

**Comment by jshlee** [comment]
we can start with RD prod

**Comment by jshlee** [comment]
i would like the quark gluon ID to be updated if needed.

**Comment by jhgoh** [comment]
catTrigger producer does not save trigger bits for now. BadMuon/BadChargedHadron filters are not saved.

**Comment by jshlee** [comment]
why not??

**Comment by jhgoh** [comment]
MET filter names are commented out in catTrigger producer cfi.
https://github.com/vallot/CATTools/blob/cat80x/CatProducer/python/producers/triggerProducer_cfi.py
Instead of catTrigger producer, we are keeping the original TriggerResults. (no information loss)

BadMuon/Ch.Hadron filters are produced with EDProducers, 'keep bool_BadMuonFitler_*_*' is missing in catEventContent_cff.py

**Comment by jshlee** [comment]
original TriggerResults was quite large

**Comment by jhgoh** [comment]
We are keeping original TriggerResults anyway. Switch to catTrigger?

```
edmDumpEventContent test/catTuple.root 
Type                                  Module                      Label           Process   
--------------------------------------------------------------------------------------------
edm::TriggerResults                   "TriggerResults"            ""              "HLT"     
double                                "fixedGridRhoFastjetAll"    ""              "RECO"    
edm::TriggerResults                   "TriggerResults"            ""              "RECO"    
pat::PackedTriggerPrescales           "patTrigger"                ""              "RECO"    
edm::TriggerResults                   "TriggerResults"            ""              "CAT"     
int                                   "lumiMask"                  ""              "CAT"     
int                                   "catVertex"                 "nGoodPV"       "CAT"     
int                                   "catVertex"                 "nPV"           "CAT"     
vector<cat::Electron>                 "catElectrons"              ""              "CAT"     
vector<cat::FatJet>                   "catFatJets"                ""              "CAT"     
vector<cat::Jet>                      "catJets"                   ""              "CAT"     
vector<cat::Jet>                      "catJetsPuppi"              ""              "CAT"     
vector<cat::MET>                      "catMETs"                   ""              "CAT"     
vector<cat::MET>                      "catMETsPuppi"              ""              "CAT"     
vector<cat::Muon>                     "catMuons"                  ""              "CAT"     
vector<cat::Photon>                   "catPhotons"                ""              "CAT"     
vector<cat::SecVertex>                "catSecVertexs"             ""              "CAT"     
vector<cat::SecVertex>                "catDstars"                 "D0Cand"        "CAT"     
vector<cat::SecVertex>                "catDstars"                 "DstarCand"     "CAT"     
vector<cat::SecVertex>                "catDstars"                 "JpsiCand"      "CAT"     
vector<cat::SecVertex>                "catDstars"                 "JpsiMVACand"   "CAT"     
vector<pat::TriggerObjectStandAlone>    "catTrigger"                ""              "CAT"     
vector<reco::Vertex>                  "catVertex"                 ""              "CAT"     
```

**Comment by jshlee** [comment]
nah its ok

**Comment by jshlee** [comment]
@geonmo - is both catSecVertexs and catDstars needed?
can you merge into one and reduce size by placing tighter cuts

**Comment by jhgoh** [comment]
Recipe for the workarea setup is created. https://github.com/vallot/CATTools/wiki#2016-december-v8-0-3-in-preparation
This is not final recipe.

**Comment by jhgoh** [comment]
Pseudotop fix (already known issue) is merged to cmssw PR.

**Comment by jhgoh** [comment]
CMSSW part seem to be complete. closing this issue.
