### ISSUE TITLE
invalid p4 in electrons

### ISSUE THREAD

**Issue by jhgoh** [vallot/CATTools#633]
some electron have invalid four momentum, nan
Can be from smearing.

**Comment by jhgoh** [comment]
nan occurs for the soft electrons, pT < 5GeV where the smearing does not work.
discussion and solution from HN: https://hypernews.cern.ch/HyperNews/CMS/get/egamma/1682/2/1/1/1.html

A PR is under preparation, fall back to original p4 when nan appears.

**Comment by jshlee** [comment]
can we just drop pT < 5GeV electrons? does anyone use this?

**Comment by jhgoh** [comment]
No one, as far as I know. Jpsi anlaysis?

**Comment by jshlee** [comment]
nope
electrons are not used to make Jpsi

**Comment by jhgoh** [comment]
Closing this issue. pt cuts will be discussed in different issue.
