### ISSUE TITLE
Broken files

### ISSUE THREAD

**Issue by jhgoh** [vallot/CATTools#679]
We discovered that there can be some troubles to read specific objects in some files.

Problem to read catGenTops, there were no problem to read other objects.
```
root://cms-xrdr.sdfarm.kr:1094///xrd/store/group/CAT/TT_TuneCUETP8M2T4_13TeV-powheg-fsrdown-pythia8/v8-0-6_RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/170303_104117/0000/catTuple_202.root
root://cms-xrdr.sdfarm.kr:1094///xrd/store/group/CAT/TTJets_TuneCUETP8M2T4_13TeV-amcatnloFXFX-pythia8/v8-0-6_RunIISummer16MiniAODv2-PUMoriond17_backup_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/170303_104621/0000/catTuple_784.root
root://cms-xrdr.sdfarm.kr:1094///xrd/store/group/CAT/TTTo2L2Nu_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8/v8-0-6_RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/170303_104739/0000/catTuple_905.root
```

**Comment by JaehoonLim** [comment]
TTTT samples run completely without segmentation error when I remove genTopProducer.
It seems this is not same problem but would you check it too?

**Comment by jhgoh** [comment]
@JaehoonLim this is addressed in #680. A crab job is submitted to be included in the v806 prod. http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=jhgoh&table=Mains&pattern=170316_033329%3Ajhgoh_crab_v8-0-6_TTTT_TuneCUETP8M2T4_13TeV-amcatnlo-pythia8

**Comment by jhgoh** [comment]
@JaehoonLim prod for the FourTops are finished.

**Comment by jhgoh** [comment]
I'll move those files to the "broken" directory. We will not loose statistics that much.

**Comment by jhgoh** [comment]
files are moved, closing this issue.
