### ISSUE TITLE
Adding deep flavor tagging information for b/c-tagging

### ISSUE THREAD

**Issue by gbyu** [vallot/CATTools#685]
As of 84x and 90x or later version, deep flavor is included in the release by default.  Before that version, for example 8_0_21 or later, b-tagging codes needs to be downloaded individually ( https://twiki.cern.ch/twiki/bin/view/CMS/DeepFlavour#DeepFlavour_recipe_for_8_0_X_X_2)

The tagger names in 8_0_21 are: 
 - btagging: deepFlavourJetTags:probudsg, deepFlavourJetTags:probb, deepFlavourJetTags:probc, deepFlavourJetTags:probbb, deepFlavourJetTags:probcc
 - ctagging: deepFlavourCMVAJetTags:probudsg, deepFlavourCMVAJetTags:probb, deepFlavourCMVAJetTags:probc, deepFlavourCMVAJetTags:probbb, deepFlavourCMVAJetTags:probcc

The tagging name changes to pfDeepCSVJetTags (<- deepFlavourJetTags) and pfDeepCMVAJetTags (<- deepFlavourCMVAJetTags) as of 84x or 90x.

**Comment by jhgoh** [comment]
To be enabled in this cff file
- https://github.com/vallot/CATTools/blob/cat80x/CatProducer/python/patTools/jetDeepFlavour_cff.py

**Comment by jhgoh** [comment]
we can close this issue.
