### ISSUE TITLE
PseudoTop in SingleTop sample

### ISSUE THREAD

**Issue by jhgoh** [vallot/CATTools#72]
I asked Chanwook to have a look on the pseudoTop in catTuple.
From his observation, pseudoTop with negative charge are not correctly filled in the event in case of single top sample (tw channel).

Currently pseudoTop producer is implemented just for the top pair production and the behavior for non-ttbar case are ill-defined.

Currently we will ignore all output from non-ttbar samples, but we need robust way to cover general cases.

**Comment by jhgoh** [comment]
Now the plan is to move PsuedoTopProducer to TQAF. Next development should go there. 
I'm closing this issue.

**Comment by jshlee** [comment]
what is TQAF?

**Comment by jhgoh** [comment]
TopQuarkAnalysisFramework in official CMSSW.
