### ISSUE TITLE
gen matching

### ISSUE THREAD

**Issue by jshlee** [vallot/CATTools#73]
For cat53x, I kept the pointers to the recoGenJet collection matched during the patJet process.
Currently catGenJet has more information on the genJet, i.e. partonFlavour and partonPdgId.

Shall we keep the recoGenJet collection or use catGenJet and save pointers to catJets.
Shall we also do the same for leptons to genParticles.

Also, for the pseudoTop and partonTop collections, if only the 4vector is needed, we can use the particle class instead of genJet and genParticles.

**Comment by jhgoh** [comment]
Regarding on the pseudoTop and partonTop collection, it has more function : mother-daughter associations. Thus one can select hadronically decaying W and leptonically (or tau) decaying W and so on.

**Comment by jshlee** [comment]
closing - reopen if this is still an issue
