### ISSUE TITLE
catEvent class?

### ISSUE THREAD

**Issue by jshlee** [vallot/CATTools#74]
should we have a class for event info?
i.e. pdfweight, pileup weight, and triggers

**Comment by jhgoh** [comment]
A container for the event variables can be made easily.
But I don't have trivial solution for trigger information. Of course one can store trigger names + results as member variables, but isn't it waste of event size to keep same names for each events?

Anyway, I think it is still worth to pack up pv info + weight variables. I'm working on that now.

**Comment by jhgoh** [comment]
Um... thinking more on this.. PDFWeight, pileup weight, trigger info are produced from different producers thus it is impossible to put them in one object.
Need unified producer if it is really needed but then the producer will be just a giant...

**Comment by jshlee** [comment]
i think the triggers as they are fine, but instead of a boolean, I want to change it to the prescale value.
For now, lets concentrate on more pressing matters

**Comment by jshlee** [comment]
i think we can close this
