### ISSUE TITLE
things to clean up

### ISSUE THREAD

**Issue by monttj** [vallot/CATTools#745]
V10 for 2018-year data analysis 
1. need to clean up the old recipe for jet smearing and b-tagging scale in Jet.cc --> Jiwon Park
2. need to clean up electron scale factor in Electron.cc in DataFormat --> Jiwon Park
3. clean up Analyzer, send announcement --> Taejeong
4. remove BadECALSlewRateMitigationFilter2016.cc and related configuration files such as metFilters_cff.py and other files (need to check) --> Jiwon Park
5. remove producers: CATDStarProducer.cc and CATSecVertexProducer.cc --> Taejeong
6. root files for kinematic reconstruction --> Jieun Choi
7. clean up CSVHelper.cc ? --> Jiwon Park
8. remove LepJetsFitterFCNH.cc --> Jiwon Park
9. event branch clean up --> Taejeong 
'keep *_catPhotons_*_*',
'keep edmTriggerResults_TriggerResults__HLT', (?)
'keep edmTriggerResults_TriggerResults__HLT2', (?)
'keep patPackedTriggerPrescales_patTrigger__*', (?)
'keep *_slimmedGenJets_*_*',
'keep recoGenParticles_prunedGenParticles_*_*',
'keep *_particleLevel_*_*', (?)
'keep *_catSecVertexs_*_*',
check file size with and without above branches --> Jieun Choi

**Comment by minerva1993** [comment]
Is there anyone knows the purpose of the lines here:
https://github.com/vallot/CATTools/blob/cat10x/CatProducer/plugins/CATElectronProducer.cc#L323-L352

**Comment by jhgoh** [comment]
> Is there anyone knows the purpose of the lines here:
> https://github.com/vallot/CATTools/blob/cat10x/CatProducer/plugins/CATElectronProducer.cc#L323-L352

These HLT-confirmation cuts had to be applied to use MVA ID because ID is optimized on top of those cuts.

**Comment by minerva1993** [comment]
> top

https://twiki.cern.ch/twiki/bin/view/CMS/MultivariateElectronIdentificationRun2Archive#Triggering_electron_MVA_details

It seems the recipe is outdated. Do we need to keep those cuts?

**Comment by jhgoh** [comment]
>     9. event branch clean up --> Taejeong
>        'keep __catPhotons____',
>        'keep edmTriggerResults_TriggerResults__HLT', (?)
>        'keep edmTriggerResults_TriggerResults__HLT2', (?)
this was necessary re-HLT samples in the past.
Anyway, this does not change event size in usual cases.

>        'keep patPackedTriggerPrescales_patTrigger___', (?)
This keeps trigger objects, necessary if you want to to trigger object - physics object matching in your analysis.

>        'keep __slimmedGenJets____',
>        'keep recoGenParticles_prunedGenParticles___*',
>        'keep __particleLevel____', (?)
This can be removed if you don't have plan for the pseudo-top related analysis.

>        'keep __catSecVertexs____',
All items related with Jpsi/D*/D0. UoS already switched to NanoAOD.

**Comment by minerva1993** [comment]
Quick check on the event size: 
drop photon, gen jet, gen particle, particle level, pat triggers -> 8.5 KB / event (TTbar sample)
drop photon, gen jet, gen particle, particle level -> 8.8 KB / event
current setting (no sec. vertex): 12 KB / event

**Comment by minerva1993** [comment]
https://github.com/minerva1993/CATTools/commit/2a856414dfa91f7110747d4ba37ef39d61897da4
I didn't make PR yet, but here's some removals and modifications for cat10x.

**Comment by jhgoh** [comment]
> > top
> 
> https://twiki.cern.ch/twiki/bin/view/CMS/MultivariateElectronIdentificationRun2Archive#Triggering_electron_MVA_details
> 
> It seems the recipe is outdated. Do we need to keep those cuts?

quickly checked this thread and the proposed code changes above.
If the purpose is just focus on latest recipe and prune out legacy ones this (and others) can be safely removed.

**Comment by minerva1993** [comment]
All those recommendations are updated in cat10x and some of them are propagated to 90x as well. Now we can close this issue.
