### ISSUE TITLE
cat object cuts and selections

### ISSUE THREAD

**Issue by jshlee** [vallot/CATTools#75]
I assume no one is using taus or photons. 
If so can we remove them.

Also, for jets and other leptons, should we place any cuts on them?

**Comment by jhgoh** [comment]
-1 
Taus and photons : TJ has some plans to use it.
Jets and leptons : Cuts can be changed.

We may go in different direction. If catTuple is aiming to top-oriented dataformat, we can introduce event/object selections and top specific tunings. I still think this is practically better but at least in this early runs, there will be some benefit to keep current structure.

**Comment by jshlee** [comment]
I would prefer catTuples to be more robust and analysis independent, so that it can be used by more people.
It seems like a lot of analysis users want a flat ntuple at the end anyways, and i feel like some of the processes can really go there.

**Comment by jshlee** [comment]
closing - reopen if this is still an issue
