### ISSUE TITLE
configuration layout

### ISSUE THREAD

**Issue by jshlee** [vallot/CATTools#77]
I wish to change the configuration layout so that everyone is happy with it.

currently PAT2CAT_cfg.py (was runCat_cfg.py) calls 
CATTools.CatProducer.catTemplate_cfg
CATTools.CatProducer.catSetup_cff

I propose the new PAT2CAT_cfg.py to call
 CATTools.CatProducer.catTemplate_cfg

then a catPATSequences_cff (name tba) with runOnMC and useMiniAOD as inputs
to configure all the PAT stuff

then a catSequences_cff (name tba) with runOnMC as input
to configure all the CAT stuff

This is just an initial proposal...
and if anyone else has better/extended ideas, please feel free to reply below.

**Comment by jshlee** [comment]
Since no one has replied, I'll go a head with this.

**Comment by monttj** [comment]
The option, "runOnMC" and "useMiniAOD" should be in PAT2CAT_cfg.py.

**Comment by jshlee** [comment]
yep, they are in PAT2CAT_cfg.py as VarParsing inputs from command line (defaults are both set to true)
