### ISSUE TITLE
about HLT 

### ISSUE THREAD

**Issue by YoungKwonJo** [vallot/CATTools#83]
In CatProducer/python/recoEventInfo_cfi.py
+++
        DoubleMu = cms.vstring(
            "HLT_Mu17_Mu8_v_", "HLT_Mu17_TkMu8_v_","HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsonVVL_v_"
        ),
+++
I would like to separate the HLT as like followings.
++++
        DoubleMu = cms.vstring(
            "HLT_Mu17_Mu8_v_", "HLT_Mu17_TkMu8_v_"
        ),
        DoubleMuIso = cms.vstring(
            "HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsonVVL_v_"
        ),
+++
In the 13 TeV, we expect very high luminosity and high pileup, 
We need to study the two-triggers as DoubleMu, DoubleMuIso.
And, we may need to check new triggers.

What do you think about it?

**Comment by jshlee** [comment]
yep, separating is fine
even having each trigger individual is fine for me
I was thinking whether if we should save the prescale value for the trigger instead of the boolean. 
Also, to do trigger studies, wouldn't you need single muon triggers as well?

**Comment by jhgoh** [comment]
No problem to add separate name, rather it's better.
Combination of multiple prescaled paths is non-trivial. Must be separated or allow only one prescaled path among mult-paths. Reasonable?

**Comment by jshlee** [comment]
@YoungKwonJo can you do the pull request. 
Yes, the combining prescale of triggers is not reasonable unless they are == 1.

**Comment by YoungKwonJo** [comment]
Current, my solution is the pull. however, we may need to think for more good solution.

https://github.com/vallot/CATTools/pull/85

And, we need to check the triggers as MuJet and ELJet.
The values are all zero in the dataset in my test-sample.
int                            "recoEventInfo"             "HLTMuEl"         "CAT"
int                            "recoEventInfo"             "HLTMuJet"        "CAT"
