### ISSUE TITLE
how to add c-tag?

### ISSUE THREAD

**Issue by YoungKwonJo** [vallot/CATTools#90]
main twiki for ctag
https://twiki.cern.ch/twiki/bin/viewauth/CMS/BTagCTagger

talk 1(Dec. 2014) 
https://indico.cern.ch/event/357463/session/0/contribution/4/material/slides/0.pdf
last talk 2 (29 January 2015)
https://indico.cern.ch/event/369384/session/1/contribution/11/material/slides/0.pdf
note
http://cms.cern.ch/iCMS/jsp/openfile.jsp?tp=draft&files=AN2012_441_v4.pdf

atlas note
http://cds.cern.ch/record/1562880/files/ATLAS-CONF-2013-068.pdf
3.1 Charm tagging

The slides in talk 1 has some tag for c-tag.

Can we add the value of ctag-related?

https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/RecoBTag/SecondaryVertex/python/candidateCombinedSecondaryVertexSoftLeptonCtagLComputer_cfi.py
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/RecoBTag/SecondaryVertex/python/pfCombinedSecondaryVertexSoftLeptonCtagLJetTags_cfi.py

However I don't know the detail, now. however if the method is ready in general cmssw, we can add it.
I am not sure, however I can see a configuration. Still,that is not added in general as like https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/RecoBTag/Configuration/python/RecoBTag_cff.py#L93.
https://github.com/cms-sw/cmssw/blob/CMSSW_7_5_X/RecoBTag/Configuration/python/RecoBTag_EventContent_cff.py

So if we use the tag, we have to wait for update.

What do you think?

+++
cf. ATLAS note
https://atlas.web.cern.ch/Atlas/GROUPS/PHYSICS/PUBNOTES/ATL-PHYS-PUB-2015-001/
https://atlas.web.cern.ch/Atlas/GROUPS/PHYSICS/CONFNOTES/ATLAS-CONF-2014-046/

**Comment by jshlee** [comment]
We can add it if you need it now.
Or we can wait for it to become official.
If it is to be saved together with the bDiscriminator pairs, it will automatically be added in cat without any code changes.

**Comment by jhgoh** [comment]
The C-tagging is going to be included in the central CMSSW. I think we can close this issue.

**Comment by geonmo** [comment]
I agree!

**Comment by jshlee** [comment]
closed!
