### ISSUE TITLE
 V7-1-1 Feb MC production

### ISSUE THREAD

**Issue by jhgoh** [vallot/CATTools#91]
Starting MC production with V7-1-1
- CMSSW_7_2_3? 73X? 74X?
  - Phys14 sample is produced with 72X
  - Need testing if we want to use 73X or later. - need volunteer
  - Phys14 not works with 75X (comment from @jshlee)
- Expecting 2 days to finish

Issues to be merged
- Isolation 03 issue #87 @jshlee 
- HLT configuration #89 

Issues not going into this production
- c-tagging #90 - N/A in CMS, future issue 
- GenTop.cc #79 - @monttj

**Comment by jhgoh** [comment]
Action items:
1. Dr. Yu - check HLT, follow links
2. @jshlee merge tags
3. Dr. Roh - validation
4. Proceed to production

(correct me if I'm wrong)

**Comment by kuyoun** [comment]
Dear all,

v7-1-1 prodution is done. 

/cms/data/xrd/store/user/youn/tag711_phy14_tbw_2025_aod
/cms/data/xrd/store/user/youn/tag711_phy14_tw_2025_aod
/cms/data/xrd/store/user/youn/tag711_phy14_dy_2025_aod
/cms/data/xrd/store/user/youn/tag711_phy14_ttbar_2025_aod
/cms/data/xrd/store/user/youn/tag711_phy14_wj_2025_aod

**Comment by jhgoh** [comment]
@dhkim82 (or somebody else) could you produce some comparison plots to the previous production?
You can use the analyzer module (https://github.com/vallot/CATTools/blob/cat72x/CatAnalyzer/plugins/CATHisAnalysis.cc) what you added into the CATTools.

**Comment by kuyoun** [comment]
Full set of ttbar is ready in the following directory
/cms/data/xrd/store/user/youn/tag711_ttbar_2025_aod

**Comment by jhgoh** [comment]
Production have finished quite long ago, but no tracking here. Can we conclude the production is completed and successful?
We don't have any kind of validation reports associated with the issue tracking.

**Comment by dhkim81** [comment]
I forget to make validation reports about production.
Do we have newest production? or If you have newest production, please tell me where can i find them.

**Comment by jhgoh** [comment]
We are not planning for new production yet.
But it will be useful to have validation plots for this production for historical purpose and workflow testing.

**Comment by jshlee** [comment]
closing - reopen if this is still an issue
