### ISSUE TITLE
about mc-matched of catmuon

### ISSUE THREAD

**Issue by YoungKwonJo** [vallot/CATTools#97]
https://github.com/vallot/CATTools/blob/cat72x/CatProducer/plugins/CATMuonProducer.cc#L127

I guess we just keep a boolean about matched/ un-matched.
We don't keep the index of genparticle as matched with muon.

If we add the index in catMuon, (I guess ) we have to update the code.
or, in catMuon ,we add(make) a 4-vector for genparticle as like a code in page 7 of the slides.
https://indico.cern.ch/event/386495/contribution/1/material/slides/0.pdf

**Comment by jhgoh** [comment]
Ref to genParticle is set here:
https://github.com/vallot/CATTools/blob/cat72x/CatProducer/plugins/CATMuonProducer.cc#L126

Also, this "MCMatching" is dR & dPt matching to muons from W/Z decay.
https://github.com/vallot/CATTools/blob/cat72x/CatProducer/plugins/CATMuonProducer.cc#L165

**Comment by jshlee** [comment]
closing - reopen if this is still an issue
