### ISSUE TITLE
74X porting

### ISSUE THREAD

**Issue by jhgoh** [vallot/CATTools#98]
Run II data taking will be done with 74X release.
We have to consider porting to 74X and corresponding MiniAOD versions.

**Comment by jshlee** [comment]
i did start this, but didnt finish yet.

**Comment by jhgoh** [comment]
Good to know. In fact, @kuyoun said she is about to start to do it.

**Comment by jshlee** [comment]
i've made a cat75x branch which works with 74x and should also work with 75x

**Comment by jshlee** [comment]
done so i'll close this
